[project]
name = "jaxfads"
dynamic = ["version"]
description = "eXponential FAmily Dynamical System"
authors = [{ name = "yuanz", email = "yuanz271@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "optax>=0.1.7",
    "numpy>=1.24.4",
    "equinox>=0.11.12",
    "omegaconf>=2.3.0",
    "rich>=14.0.0",
    "tensorflow-probability[jax]>=0.24.0,<0.26.0",
    "jax>=0.4.38,<0.7.0",
    "gearax @ git+https://github.com/yuanz271/gearax.git@29d694e66adb11c5bf6dd43c52ff5f839cd86f10",
    "jaxtyping>=0.3.2",
]

[dependency-groups]
dev = [
    "chex>=0.1.90",
    "matplotlib>=3.10.1",
    "numpydoc>=1.7.0",
    "pytest>=8.3.4",
    "ruff>=0.9.4",
    "ty>=0.0.1",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project.urls]
Repository = "https://github.com/yuanz271/jaxfads"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src/jaxfads"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
target-version = "py311"
lint.ignore = ["E501", "F722"]

[tool.numpydoc_validation]
checks = ["GL01", "SS02", "PR01", "PR10", "RT01"]
override_GL01 = "See base class"
override_PR01 = "See base class"
override_RT01 = "See base class"

